{
  description = "containerd-shim-systemd-v1: a containerd shim that runs containers as systemd units";

  inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
  inputs.gomod2nix = {
    url = "github:nix-community/gomod2nix";
    inputs.nixpkgs.follows = "nixpkgs";
  };

  outputs =
    {
      self,
      nixpkgs,
      gomod2nix,
    }:
    let
      # The shim is Linux + systemd only, so packages/devShells target Linux.
      systems = [
        "x86_64-linux"
        "aarch64-linux"
      ];
      forAllSystems = f: nixpkgs.lib.genAttrs systems (system: f nixpkgs.legacyPackages.${system});

      # mkShim builds the shim daemon and the checkexec smoke-test helper via
      # gomod2nix: the Go module set is pinned in gomod2nix.toml (regenerated by
      # `go generate`, no Nix required) instead of a single vendorHash. cgo is on
      # by default and the C sources only need libc, so the stdenv compiler
      # suffices.
      #
      # go is passed explicitly because go.mod's floor (1.23) no longer exists in
      # nixpkgs; without this, gomod2nix would try to resolve the removed go_1_23.
      mkShim =
        pkgs:
        (gomod2nix.legacyPackages.${pkgs.stdenv.hostPlatform.system}.buildGoApplication) {
          pname = "containerd-shim-systemd-v1";
          version = "0.1.0-dev";

          go = pkgs.go;

          src = pkgs.lib.cleanSourceWith {
            src = ./.;
            filter =
              path: type:
              let
                base = baseNameOf path;
              in
              !(builtins.elem base [
                "bin"
                "result"
                ".copilot"
              ])
              && !(pkgs.lib.hasSuffix ".test" base);
          };

          modules = ./gomod2nix.toml;

          subPackages = [
            "."
            "contrib/checkexec"
          ];

          # The unit tests need a live systemd bus; run them from the devShell or
          # the VM, not at build time.
          doCheck = false;

          meta = {
            description = "containerd shim that runs containers as systemd units";
            homepage = "https://github.com/cpuguy83/containerd-shim-systemd-v1";
            license = pkgs.lib.licenses.asl20;
            mainProgram = "containerd-shim-systemd-v1";
            platforms = pkgs.lib.platforms.linux;
          };
        };

      # shimModule installs the shim and points the system containerd at it.
      # systemd remains the source of truth: the shim reacts to unit state over
      # D-Bus and drives containers as transient/loaded units.
      #
      # The shim ships an `install` convenience command that writes its socket and
      # service units to /etc/systemd/system, but that path is read-only on NixOS,
      # so we declare the same two units natively here instead. They mirror what
      # `install` generates (see serviceUnit/socketUnit in service.go): a
      # socket-activated, Type=notify daemon listening on the shim API socket that
      # containerd dials.
      shimModule =
        { pkgs, lib, ... }:
        let
          shim = mkShim pkgs;
          bin = "${shim}/bin/containerd-shim-systemd-v1";
          # The shim API socket containerd dials. This must match the address the
          # shim's `start` command reports to containerd, which is its built-in
          # default (see defaultAddress in service.go).
          apiSocket = "/run/containerd/s/containerd-shim-systemd-v1.sock";
          # containerd's own endpoints, which the shim talks back to.
          containerdSock = "/run/containerd/containerd.sock";
          # Where the shim keeps runc state; the shim creates it on start.
          root = "/run/containerd/io.containerd.systemd.v1";
        in
        {
          environment.systemPackages = [
            shim
            pkgs.runc
            pkgs.nerdctl
            pkgs.cni-plugins
            # The CNI bridge plugin shells out to iptables to set up container
            # networking. nerdctl records the invoking shell's PATH into the CNI
            # OCI hook, so iptables must be on the interactive PATH or a networked
            # `nerdctl run` fails with "failed to locate iptables".
            pkgs.iptables
          ];

          virtualisation.containerd.enable = true;

          # containerd execs `containerd-shim-systemd-v1 start`, and the shim
          # daemon execs runc; make both resolvable from containerd's PATH.
          systemd.services.containerd.path = [
            shim
            pkgs.runc
          ];

          # nerdctl looks for CNI plugins under /opt/cni/bin by default.
          systemd.tmpfiles.rules = [
            "L+ /opt/cni/bin - - - - ${pkgs.cni-plugins}/bin"
          ];

          # Socket activation: containerd connecting to apiSocket starts the shim.
          systemd.sockets.containerd-shim-systemd-v1 = {
            description = "containerd shim API socket for containerd-shim-systemd-v1";
            wantedBy = [ "sockets.target" ];
            socketConfig = {
              ListenStream = apiSocket;
              SocketMode = "0700";
              PassCredentials = true;
              PassSecurity = true;
            };
          };

          # The shim daemon. Type=notify + socket activation, matching what the
          # shim's own installer would produce.
          systemd.services.containerd-shim-systemd-v1 = {
            description = "containerd shim service that uses systemd to manage containers";
            requires = [ "containerd-shim-systemd-v1.socket" ];
            after = [
              "containerd-shim-systemd-v1.socket"
              "containerd.service"
            ];
            path = [ pkgs.runc ];
            serviceConfig = {
              Type = "notify";
              Environment = "UNIT_NAME=%n";
              ExecStart = lib.concatStringsSep " " [
                bin
                "--address=${containerdSock}"
                "serve"
                "--ttrpc-address=${containerdSock}.ttrpc"
                "--debug"
                "--root=${root}"
                "--log-mode=journald"
              ];
            };
          };
        };

      # vmModule layers a throwaway, isolated end-to-end environment on top of
      # shimModule: docker for general use, autologin, and enough resources to
      # pull images and run containers.
      vmModule =
        {
          modulesPath,
          ...
        }:
        {
          imports = [ "${modulesPath}/virtualisation/qemu-vm.nix" ];

          networking.hostName = "shim-dev";

          # docker is available for general use. Driving the shim *through* docker
          # (docker --default-runtime=io.containerd.systemd.v1) needs a patched
          # dockerd (see the repo Dockerfile), so validate the shim via
          # `nerdctl --runtime io.containerd.systemd.v1` or `ctr` against the
          # system containerd instead.
          virtualisation.docker.enable = true;

          services.getty.autologinUser = "root";
          users.users.root.password = "";

          networking.firewall.enable = false;

          virtualisation = {
            memorySize = 4096;
            cores = 4;
            diskSize = 8192;
            graphics = false;
          };

          system.stateVersion = "24.11";
        };
    in
    {
      packages = forAllSystems (pkgs: {
        default = mkShim pkgs;
        containerd-shim-systemd-v1 = mkShim pkgs;
      });

      overlays.default = final: prev: {
        containerd-shim-systemd-v1 = mkShim final;
      };

      nixosModules.default = shimModule;

      nixosConfigurations.vm = nixpkgs.lib.nixosSystem {
        system = "x86_64-linux";
        modules = [
          shimModule
          vmModule
        ];
      };

      apps.x86_64-linux.vm = {
        type = "app";
        program = "${self.nixosConfigurations.vm.config.system.build.vm}/bin/run-shim-dev-vm";
      };

      devShells = forAllSystems (pkgs: {
        default = pkgs.mkShell {
          packages = [
            pkgs.go
            pkgs.gcc
            pkgs.gnumake
            pkgs.git
            pkgs.gotestsum
            pkgs.containerd
            pkgs.runc
            pkgs.nerdctl
            pkgs.cni-plugins
            pkgs.docker-client
          ];
        };
      });

      checks = forAllSystems (pkgs: {
        shim = mkShim pkgs;
      });
    };
}
