schema = 3

[mod]
  [mod."github.com/Microsoft/go-winio"]
    version = "v0.5.2"
    hash = "sha256-g+kEivzu+sIaO5fDGR4RCpm3LmJSzmsAO16wAzBnP6c="
  [mod."github.com/Microsoft/hcsshim"]
    version = "v0.9.4"
    hash = "sha256-yaLaddAE1U5e2KXzsIlw0bcyAAsvgjQvg9VOJCCqIyo="
  [mod."github.com/cenkalti/backoff/v4"]
    version = "v4.1.3"
    hash = "sha256-u6MEDopHoTWAZoVvvXOKnAg++xre53YgQx0gmf6t2KU="
  [mod."github.com/cilium/ebpf"]
    version = "v0.9.1"
    hash = "sha256-D1/r5SX7FVkX7cu7hgh9n9JGsJR9C5KfuO64BTciHBY="
  [mod."github.com/containerd/cgroups"]
    version = "v1.0.4"
    hash = "sha256-dfPas2IXzDeOCWsX0eFFikQyJH+ZPZfibbsFjB9/mKM="
  [mod."github.com/containerd/console"]
    version = "v1.0.3"
    hash = "sha256-4p4u/rS7G4KKbIcZaVMqE1OtSoNlOpmcYFwO0ZEH/V0="
  [mod."github.com/containerd/containerd"]
    version = "v1.6.8"
    hash = "sha256-rSOX8pBVT0r6rcVS9/XcwO3IsVHhd7ZEXC8QN4y1JlE="
  [mod."github.com/containerd/continuity"]
    version = "v0.2.2"
    hash = "sha256-8vLsgGIzPz9ne/dotHfjUNZ6cirB4zDyZr+mx6vbpbA="
  [mod."github.com/containerd/fifo"]
    version = "v1.0.0"
    hash = "sha256-OMCD11bviVvsNsYWl4H5LUR7Y/3p2PDXPZLJSlby0tA="
  [mod."github.com/containerd/go-runc"]
    version = "v1.0.0"
    hash = "sha256-dgD2VZ8Y5/R5wlmKj194N8BOf6SXRu/sGqjV/n8DY3Y="
  [mod."github.com/containerd/ttrpc"]
    version = "v1.1.0"
    hash = "sha256-2j6DXKyEfBJZW0KBGiJhZYBNCRdqW/gvh77NuuO4+Y0="
  [mod."github.com/containerd/typeurl"]
    version = "v1.0.2"
    hash = "sha256-QJifsbwYVYT1onMAMa9dJRxWTPKqZ6NTC8HS+TrtbnM="
  [mod."github.com/coreos/go-systemd"]
    version = "v0.0.0-20191104093116-d3cd4ed1dbcf"
    hash = "sha256-HEnyJ9uxZdlZb2lG8YwxYuuYTCW8PpxUhADqEwNlN5U="
  [mod."github.com/coreos/go-systemd/v22"]
    version = "v22.7.0"
    hash = "sha256-roA/Wcis73cIFpsNN3SbXhs9uLZbfRc9z0RQ6hDrWpU="
  [mod."github.com/docker/go-events"]
    version = "v0.0.0-20190806004212-e31b211e4f1c"
    hash = "sha256-lJ3XZMNLYOn2iH7v1+REjq+DlrPaLkXn0nGIN8gn9SU="
  [mod."github.com/docker/go-units"]
    version = "v0.4.0"
    hash = "sha256-f9d4OzZqYcsgP2gqutTPRju5BVFz4/pzefgSipGSD00="
  [mod."github.com/go-logr/logr"]
    version = "v1.2.3"
    hash = "sha256-2L7k6GfrcW3GXXYr1FYIu20aZBjIF0cTKdte6D4riH8="
  [mod."github.com/go-logr/stdr"]
    version = "v1.2.2"
    hash = "sha256-rRweAP7XIb4egtT1f2gkz4sYOu7LDHmcJ5iNsJUd0sE="
  [mod."github.com/godbus/dbus/v5"]
    version = "v5.1.0"
    hash = "sha256-xOCMJpQK3KTmHTPn/CdqI4j0eENCtMmJDgAIoYqYOEY="
  [mod."github.com/gogo/googleapis"]
    version = "v1.4.0"
    hash = "sha256-BN8QFC0dB8Rw21ljuN8hkYeh6e9TYSgt1JePxzTLd4I="
  [mod."github.com/gogo/protobuf"]
    version = "v1.3.2"
    hash = "sha256-pogILFrrk+cAtb0ulqn9+gRZJ7sGnnLLdtqITvxvG6c="
  [mod."github.com/golang/groupcache"]
    version = "v0.0.0-20210331224755-41bb18bfe9da"
    hash = "sha256-7Gs7CS9gEYZkbu5P4hqPGBpeGZWC64VDwraSKFF+VR0="
  [mod."github.com/golang/protobuf"]
    version = "v1.5.2"
    hash = "sha256-IVwooaIo46iq7euSSVWTBAdKd+2DUaJ67MtBao1DpBI="
  [mod."github.com/google/uuid"]
    version = "v1.2.0"
    hash = "sha256-TPn8gHg0Gb2GZUNxVdLyqlWgTX1QRvmseGwIjtKLmCM="
  [mod."github.com/grpc-ecosystem/grpc-gateway/v2"]
    version = "v2.11.2"
    hash = "sha256-ptALd6cQC+0SJ1P/FdTE4PVuMm9+iUc9FgXh75W99UI="
  [mod."github.com/klauspost/compress"]
    version = "v1.11.13"
    hash = "sha256-2D3XUYQ9zd3mNlVNypGnJ8w0Q9OQtM/hE0PmYbDc2Lo="
  [mod."github.com/moby/locker"]
    version = "v1.0.1"
    hash = "sha256-OcpbO3fLe0WtLDZFF1ntxoEBlEDjyoA8q8mVAQ0TLB8="
  [mod."github.com/moby/sys/mountinfo"]
    version = "v0.6.2"
    hash = "sha256-Dz2dYMPP8dmijrrbG28HIdjXzgkPw4KVsMbdKqhd4Uk="
  [mod."github.com/moby/sys/signal"]
    version = "v0.6.0"
    hash = "sha256-y09taIFqXq+N8phAoOU99hSWtJSJCzUPTIiqzoKVEDQ="
  [mod."github.com/opencontainers/go-digest"]
    version = "v1.0.0"
    hash = "sha256-cfVDjHyWItmUGZ2dzQhCHgmOmou8v7N+itDkLZVkqkQ="
  [mod."github.com/opencontainers/image-spec"]
    version = "v1.0.3-0.20211202183452-c5a74bcca799"
    hash = "sha256-l6EuKVqMhwKVZO1P6bbETDHklLB+Acscno5KENG6vNM="
  [mod."github.com/opencontainers/runc"]
    version = "v1.1.2"
    hash = "sha256-8w6jMLjcgBB5sqqtPktiANdi9gRV0o8bzHIj+KpVf6w="
  [mod."github.com/opencontainers/runtime-spec"]
    version = "v1.0.3-0.20210326190908-1c3f411f0417"
    hash = "sha256-GI8af1UKF39HTqXOaj6HySectwHOmMTKcAqpF8hH86s="
  [mod."github.com/opencontainers/selinux"]
    version = "v1.10.1"
    hash = "sha256-FqVGbRtfn9PBbsXxl1YbWIrHrKYvEW3niUho/cHcbBg="
  [mod."github.com/pelletier/go-toml"]
    version = "v1.9.5"
    hash = "sha256-RJ9K1BTId0Mled7S66iGgxHkZ5JKEIsrrNaEfM8aImc="
  [mod."github.com/pkg/errors"]
    version = "v0.9.1"
    hash = "sha256-mNfQtcrQmu3sNg/7IwiieKWOgFQOVVe2yXgKBpe/wZw="
  [mod."github.com/sirupsen/logrus"]
    version = "v1.9.0"
    hash = "sha256-xOwGFsYGIxNiurS8Zue8mhlFK/G7U1LVFFrv4vcr1GM="
  [mod."go.opencensus.io"]
    version = "v0.23.0"
    hash = "sha256-R3O9GyNtv6j0ic7s+2xkLLaLzbJEop0Otj1nJDFBjsg="
  [mod."go.opentelemetry.io/otel"]
    version = "v1.9.0"
    hash = "sha256-rP9kSnsGDaUDiYrQkBchHPLHGBJv5D16lR+UJ4wIzw8="
  [mod."go.opentelemetry.io/otel/exporters/otlp/internal/retry"]
    version = "v1.9.0"
    hash = "sha256-QqgSBRgABKVAJTXaAnRYbaPZMtYHmyg7efb+T+Bikd0="
  [mod."go.opentelemetry.io/otel/exporters/otlp/otlptrace"]
    version = "v1.9.0"
    hash = "sha256-WevrcyW3q8j5Nclwe8DdjgHfDKkIhNpcbeNPu8+LdNs="
  [mod."go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc"]
    version = "v1.9.0"
    hash = "sha256-E/FCEetZlRDVmasnntL2eXGaIGcIwEjpLkqh6XwmyrA="
  [mod."go.opentelemetry.io/otel/sdk"]
    version = "v1.9.0"
    hash = "sha256-c6quzhWD6Wqt5xmB9KrmNoVmStCspoCaPAwjNiX17CA="
  [mod."go.opentelemetry.io/otel/trace"]
    version = "v1.9.0"
    hash = "sha256-zHQ67CcTsSVukBH3MKIycJKeWYXSnEgql/Jxq8ixjLI="
  [mod."go.opentelemetry.io/proto/otlp"]
    version = "v0.19.0"
    hash = "sha256-yOixDEwd/ZdmT3XcCBGqDc4n0+4bwT7zsXc+ISbFOkI="
  [mod."golang.org/x/net"]
    version = "v0.0.0-20220812174116-3211cb980234"
    hash = "sha256-v/Qep/W6lw6IurR+R2V0AN/MlQUROLnEaWeeuwY8sg8="
  [mod."golang.org/x/sync"]
    version = "v0.0.0-20220722155255-886fb9371eb4"
    hash = "sha256-ZZyIlxh+nqsOiWHstW7eHXN7RhHnbSL2eDIzcve07Q0="
  [mod."golang.org/x/sys"]
    version = "v0.1.0"
    hash = "sha256-nZbEJ/2PuWrDLD4ujeVvcFGoIsfVoIH/Lcp4FjD7hpU="
  [mod."golang.org/x/text"]
    version = "v0.3.7"
    hash = "sha256-XH2pUzzQx95O0rak00grQvfACfL+EmZiV7ZzJBkX+XY="
  [mod."google.golang.org/genproto"]
    version = "v0.0.0-20220817144833-d7fd3f11b9b1"
    hash = "sha256-ZIratWdNIiXzB5YOfi4Mjmmk6BFmWsjFTRdAZfkDEMg="
  [mod."google.golang.org/grpc"]
    version = "v1.48.0"
    hash = "sha256-sF2W+L5IHiCO1t/SsHpmht1tPiXJ2RBiiosk+BngfKA="
  [mod."google.golang.org/protobuf"]
    version = "v1.28.1"
    hash = "sha256-sTJYgvlv5is7vHNxcuigF2lNASp0QonhUgnrguhfHSU="
