// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        v7.35.1
// source: options/options.proto

package options

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogMode int32

const (
	LogMode_DEFAULT  LogMode = 0
	LogMode_JOURNALD LogMode = 1
	LogMode_STDIO    LogMode = 2
	LogMode_NULL     LogMode = 3
)

// Enum value maps for LogMode.
var (
	LogMode_name = map[int32]string{
		0: "DEFAULT",
		1: "JOURNALD",
		2: "STDIO",
		3: "NULL",
	}
	LogMode_value = map[string]int32{
		"DEFAULT":  0,
		"JOURNALD": 1,
		"STDIO":    2,
		"NULL":     3,
	}
)

func (x LogMode) Enum() *LogMode {
	p := new(LogMode)
	*p = x
	return p
}

func (x LogMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogMode) Descriptor() protoreflect.EnumDescriptor {
	return file_options_options_proto_enumTypes[0].Descriptor()
}

func (LogMode) Type() protoreflect.EnumType {
	return &file_options_options_proto_enumTypes[0]
}

func (x LogMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogMode.Descriptor instead.
func (LogMode) EnumDescriptor() ([]byte, []int) {
	return file_options_options_proto_rawDescGZIP(), []int{0}
}

type CreateOptions struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	LogMode        LogMode                `protobuf:"varint,1,opt,name=log_mode,json=logMode,proto3,enum=containerd.systemd.v1.LogMode" json:"log_mode,omitempty"`
	SdNotifyEnable bool                   `protobuf:"varint,2,opt,name=sd_notify_enable,json=sdNotifyEnable,proto3" json:"sd_notify_enable,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateOptions) Reset() {
	*x = CreateOptions{}
	mi := &file_options_options_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOptions) ProtoMessage() {}

func (x *CreateOptions) ProtoReflect() protoreflect.Message {
	mi := &file_options_options_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOptions.ProtoReflect.Descriptor instead.
func (*CreateOptions) Descriptor() ([]byte, []int) {
	return file_options_options_proto_rawDescGZIP(), []int{0}
}

func (x *CreateOptions) GetLogMode() LogMode {
	if x != nil {
		return x.LogMode
	}
	return LogMode_DEFAULT
}

func (x *CreateOptions) GetSdNotifyEnable() bool {
	if x != nil {
		return x.SdNotifyEnable
	}
	return false
}

var File_options_options_proto protoreflect.FileDescriptor

const file_options_options_proto_rawDesc = "" +
	"\n" +
	"\x15options/options.proto\x12\x15containerd.systemd.v1\"t\n" +
	"\rCreateOptions\x129\n" +
	"\blog_mode\x18\x01 \x01(\x0e2\x1e.containerd.systemd.v1.LogModeR\alogMode\x12(\n" +
	"\x10sd_notify_enable\x18\x02 \x01(\bR\x0esdNotifyEnable*9\n" +
	"\aLogMode\x12\v\n" +
	"\aDEFAULT\x10\x00\x12\f\n" +
	"\bJOURNALD\x10\x01\x12\t\n" +
	"\x05STDIO\x10\x02\x12\b\n" +
	"\x04NULL\x10\x03B@Z>github.com/cpuguy83/containerd-shim-systemd-v1/options;optionsb\x06proto3"

var (
	file_options_options_proto_rawDescOnce sync.Once
	file_options_options_proto_rawDescData []byte
)

func file_options_options_proto_rawDescGZIP() []byte {
	file_options_options_proto_rawDescOnce.Do(func() {
		file_options_options_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_options_options_proto_rawDesc), len(file_options_options_proto_rawDesc)))
	})
	return file_options_options_proto_rawDescData
}

var file_options_options_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_options_options_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_options_options_proto_goTypes = []any{
	(LogMode)(0),          // 0: containerd.systemd.v1.LogMode
	(*CreateOptions)(nil), // 1: containerd.systemd.v1.CreateOptions
}
var file_options_options_proto_depIdxs = []int32{
	0, // 0: containerd.systemd.v1.CreateOptions.log_mode:type_name -> containerd.systemd.v1.LogMode
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_options_options_proto_init() }
func file_options_options_proto_init() {
	if File_options_options_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_options_options_proto_rawDesc), len(file_options_options_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_options_options_proto_goTypes,
		DependencyIndexes: file_options_options_proto_depIdxs,
		EnumInfos:         file_options_options_proto_enumTypes,
		MessageInfos:      file_options_options_proto_msgTypes,
	}.Build()
	File_options_options_proto = out.File
	file_options_options_proto_goTypes = nil
	file_options_options_proto_depIdxs = nil
}
