name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  integration:
    runs-on: ubuntu-18.04
    timeout-minutes: 40
    defaults:
      run:
        working-directory: src/github.com/cpuguy83/containerd-shim-systemd/v1
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17.3'
      - uses: actions/checkout@v2
        with:
          path: src/github.com/cpuguy83/containerd-shim-systemd/v1
      - uses: actions/checkout@v2
        with:
          path: src/github.com/containerd/containerd
          repository: containerd/containerd
          ref: v1.6.0-beta.1
      - name: Install gotestsum
        run: go install gotest.tools/gotestsum@latest
      - name: Install required packages
        run: sudo apt-get update && sudo apt-get install -y criu
      - name: get containerd
        run: |
            set -ex
            curl -SLf https://github.com/containerd/containerd/releases/download/v${VERSION}/containerd-${VERSION}-linux-amd64.tar.gz | tar -xvz
            sudo systemctl stop containerd
            cd bin
            for i in *; do sudo mv $i $(command -v $i); done
            sudo systemctl start containerd
        env:
          VERSION: 1.6.0-beta.1
      - name: install
        run: |
          make build
          sudo make install
          sudo $(command -v containerd-shim-systemd-v1) install
      - name: test
        run: |
          export GOPATH=${GITHUB_WORKSPACE}
          cd "${GITHUB_WORKSPACE}/src/github.com/containerd/containerd"
          sudo -E PATH=${PATH} make integration EXTRA_TESTFLAGS=${EXTRA_TESTFLAGS} GOTEST="gotestsum --"
        env:
          TEST_RUNTIME: io.containerd.systemd.v1
          RUNC_FLAVOR: runc
          GOTESTSUM_JUNITFILE: ${{github.workspace}}/junit.xml
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        if: always() # always run even if the previous step fails
        with:
          report_paths: ${{github.workspace}}/junit.xml
      - name: debug
        if: ${{ failure() }}
        run: |
          sudo journalctl --system -u containerd-shim-systemd-v1 | tee ${GITHUB_WORKSPACE}/containerd-shim-systemd-v1.log
      - uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with:
          name: daemon-log
          path: ${{github.workspace}}/containerd-shim-systemd-v1.log