name: CI
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  integration:
    runs-on: ubuntu-20.04
    timeout-minutes: 40
    defaults:
      run:
        working-directory: src/github.com/cpuguy83/containerd-shim-systemd/v1
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: "1.17.3"
      - uses: actions/checkout@v2
        with:
          path: src/github.com/cpuguy83/containerd-shim-systemd/v1
      - uses: actions/checkout@v2
        with:
          path: src/github.com/containerd/containerd
          repository: containerd/containerd
          ref: v1.6.8
      - name: Install gotestsum
        run: go install gotest.tools/gotestsum@latest
      - name: Install required packages
        run: |
          set -e -x
          sudo add-apt-repository ppa:criu/ppa
          sudo apt-get update
          sudo apt-get install -y criu
      - name: get containerd
        run: |
          set -ex
          curl -SLf https://github.com/containerd/containerd/releases/download/v${VERSION}/containerd-${VERSION}-linux-amd64.tar.gz | tar -xvz
          sudo systemctl stop containerd
          cd bin
          for i in *; do sudo mv $i $(command -v $i); done
          sudo systemctl start containerd
        env:
          VERSION: 1.6.8
      - name: install
        run: make test-daemon
      - name: test
        run: |
          set -e -x
          export GOPATH="${GITHUB_WORKSPACE}"
          cd "${GITHUB_WORKSPACE}/src/github.com/containerd/containerd"
          sudo -E PATH="${PATH}" -E GOPATH="${GOPATH}" make integration EXTRA_TESTFLAGS="${EXTRA_TESTFLAGS}" GOTEST="${GOTEST}"
        env:
          TEST_RUNTIME: io.containerd.systemd.v1
          RUNC_FLAVOR: runc
          GOTESTSUM_JUNITFILE: ${{github.workspace}}/junit.xml
          EXTRA_TESTFLAGS: "-no-criu"
          GOTEST: gotestsum --format=standard-verbose --
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        if: always() # always run even if the previous step fails
        with:
          report_paths: ${{github.workspace}}/junit.xml
      - name: debug
        if: ${{ failure() }}
        run: |
          sudo systemctl kill -s USR1 containerd-shim-systemd-v1
          sleep 1
          sudo journalctl --system -u containerd-shim-systemd-v1 | tee ${GITHUB_WORKSPACE}/containerd-shim-systemd-v1.log
          sudo chown $(id -u):$(id -g) /tmp/*containerd-shim-systemd-v1-goroutines*
      - uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with:
          name: daemon-log
          path: ${{github.workspace}}/containerd-shim-systemd-v1.log
      - uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with:
          name: goroutines
          path: /tmp/*containerd-shim-systemd-v1-goroutines*
